### ISSUE TITLE
Python type for JSON columns is dict

### ISSUE THREAD

**Issue by andrew222651** [agronholm/sqlacodegen#212]
In a PostgreSQL database, a JSON or JSONB column is converted to (with the dataclass output)
`col_name: Optional[dict] = field(default=None, metadata={'sa': Column(JSONB)})`. Usually JSON/JSONB fields correspond to Python types that you get from `json.dumps`: nested list, dict, int, etc., not just `dict`.

**Comment by agronholm** [comment]
Sqlacodegen just uses whatever Python type comes from `column.type.python_type`. You should probably report this as a bug against SQLAlchemy itself. I recently got a similar issue fixed with a PR that implements `python_type` for the `UUID` column type.

**Comment by CaselIT** [comment]
for reference this was reported here https://github.com/sqlalchemy/sqlalchemy/discussions/10177

**Comment by tbrugere-nrjx** [comment]
For anyone looking for a quickfix, just write a plugin that at the start does

```python
# fix  for https://github.com/agronholm/sqlacodegen/issues/212
JSON.python_type = Any #type:ignore
JSONB.python_type = Any #type:ignore
```

(or some better type instead)

**Comment by rreeves8** [comment]
Why is this marked as closed?  Seems this issue is relevant and still present - `dict` is not the correct type to use

**Comment by andrew222651** [comment]
> Why is this marked as closed? Seems this issue is relevant and still present - `dict` is not the correct type to use

Because it's really a SQLAlchemy issue

**Comment by CaselIT** [comment]
was fixed in 2.1 to return object instead https://github.com/sqlalchemy/sqlalchemy/issues/10646
